# Site settings
course_name: Developper Abuse
course_description: "In this course you shall learn the ways of which certain organizations may choose to abuse and exploit their employees in the Computer Science field."
course_semester: "Fall 2023"

baseurl: "/ENG-ZP3" # the subpath of your site, e.g. /blog/
url: "https://noahgendron.github.io/" # the base hostname & protocol for your site

schoolname: "Crunchool"
schoolurl: "https://noahgendron.github.io/"
twitter_username: fakeNameTotallyReal 

address: |
    School of Crunchy Development
    Crunchool
    Quebec

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
